export const INITIAL_NUMBER_OF_PRIMES = 200
export const MIN_NUMBER_OF_PRIMES = 50
export const MAX_NUMBER_OF_PRIMES = 1000
export const STEP_NUMBER_OF_PRIMES = 50
export const NUMBER_OF_PRIME_SHUFFLE_VISUAL_STEPS = 10
