import { Footer } from '../Components/Layout/Footer';
import { Navbar } from '../Components/Layout/Navbar';
import '../styles/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="grid min-h-svh grid-rows-[auto_1fr_auto]">
        <Navbar />
        <div className="grow">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
